spring:
   datasource:
      url: jdbc:mysql://localhost:3306/olx_masterdata
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: Krishna@Zensar47
   jpa:
     hibernate.ddl-auto: update
     properties:
        hibernate:
           dialect: org.hibernate.dialect.MySQL8Dialect
